COMPONENT_SRCDIRS += ../cmocka/src ./
COMPONENT_ADD_INCLUDEDIRS += ../cmocka/include ./include

ifeq ($(CONFIG_STDK_IOT_CORE_BSP_SUPPORT_ESP8266),y)
	CFLAGS += -DHAVE_CONFIG_H
	COMPONENT_SRCDIRS += ./esp8266
	COMPONENT_ADD_INCLUDEDIRS += ./esp8266
endif
